### ISSUE TITLE
Add `event` to subscription event

### ISSUE THREAD

**Issue by allevo** [marco-ippolito/fiume#171]
## Use case
I would like to implement event sourcing.

```ts
const machine = StateMachine.from(states, {
	context: { events: [] },
});
machine.subscribe(({ context, event }) => {
	context.events.push(event)
});
```

`subscription` callback is invoked when a new state is reached. The `subscription` callback is invoked with `context`, `sharedData`, and `currentStateId`, available on the machine instance. The only element not available is the event. This limits the capability because I cannot update the `context` using `event`.

## Proposed enhancement
From type perspective:
```ts
export type SubscriptionCallbackInput<
	TContext = unknown,
	TEvent = unknown, // added
	TSharedData = unknown,
> = {
	context: TContext;
	currentStateId: StateIdentifier;
	sharedData: TSharedData;
	event?: TEvent // added
};
```

I can provide a PR to address this.

**Comment by marco-ippolito** [comment]
soonds like a good idea, pr welcome
