### ISSUE TITLE
not working on browser - Uncaught TypeError: (0 , import_crypto.randomUUID) is not a function

### ISSUE THREAD

**Issue by tomer-yechiel** [marco-ippolito/fiume#33]
I am trying to run the library on the browser and i am getting that error.
This issue can be solve with polyfile but i prefer not to go that route.
If i will find a solution i will submit a pr

**Comment by marco-ippolito** [comment]
What error are you receiving?

**Comment by marco-ippolito** [comment]
randomUUID should be available on the browser, thats weird https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by tomer-yechiel** [comment]
> randomUUID should be available on the browser, thats weird https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

you can't import crypto in the browser.
crypto exist on the window object(on modern browsers)
one solution is to check if the code is running on the browser or node and act accordingly

**Comment by marco-ippolito** [comment]
Then I guess it should try to dynamically import crypto and if fails fall back go window.crypto

**Comment by tomer-yechiel** [comment]
trying to do that

**Comment by marco-ippolito** [comment]
Actually Node has webcrypto api so crypto is a global that doesnt need to be imported, should be fixed with my next pr

**Comment by marco-ippolito** [comment]
relased the fix, on 0.2.3

**Comment by tomer-yechiel** [comment]
thanks
